services:
  backend:
    build: ./BE
    ports:
      - '8080:8080'
    env_file:
      - ./BE/.env
    volumes:
      - ./data/logs:/app/data/logs
    restart: unless-stopped

  frontend:
    build: ./FE
    ports:
      - '3000:3000'
    env_file:
      - ./FE/.env
    restart: unless-stopped
    depends_on:
      - backend
